# Travis configuration for annotation-service
#
#  * decrypt service account credentials
#  * install the Google Cloud SDK command line tools (gcloud)
#  * cache the gcloud installation and setup
#  * test and build the go code
#  * on success, deploy the result when the origin branch or tag matches
#    a supported deployment target.
#
language: go

# Without this, annotator.sh fails, related to gcloud.
sudo: required

go:
- 1.8

before_install:
- go get github.com/mattn/goveralls
- go get github.com/wadey/gocovmerge

# This installs gcloud, sets up devappserver.
- $TRAVIS_BUILD_DIR/annotator.sh

# NB: Encrypted values are not defined in forks or pull requests.
#
# Decrypt the tar archive containing the GCP service account key files.
# After unpacking, there should be one service account key file for every GCP
# project referenced in the "deploy" section. These keys authenticate the
# gcloud deploy operations.
#
# Reusing the etl-travis-deploy keys, since we need identical capabilities.
- travis/decrypt.sh "$encrypted_ca29bb0d9214_key" "$encrypted_ca29bb0d9214_iv" keys/service-accounts.tar.enc
  /tmp/service-accounts.tar /tmp
- tar tvf /tmp/service-accounts.tar
- echo Branch is ${TRAVIS_BRANCH} and Tag is $TRAVIS_TAG

# These directories will be cached on successful "script" builds, and restored,
# if available, to save time on future builds.
cache:
  directories:
  - $HOME/google-cloud-sdk/

script:
- export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
- export APPENGINE_DEV_APPSERVER="${HOME}/google-cloud-sdk/bin/dev_appserver.py"
- source "${HOME}/google-cloud-sdk/path.bash.inc"

- go test -covermode=count -coverprofile=handler.cov -v github.com/m-lab/annotation-service/handler
- go test -covermode=count -coverprofile=loader.cov -v github.com/m-lab/annotation-service/loader
- go test -covermode=count -coverprofile=metrics.cov -v github.com/m-lab/annotation-service/metrics
- go test -covermode=count -coverprofile=parser.cov -v github.com/m-lab/annotation-service/parser
- go test -covermode=count -coverprofile=search.cov -v github.com/m-lab/annotation-service/search

# Coveralls
- $HOME/gopath/bin/gocovmerge handler.cov loader.cov parser.cov search.cov > merge.cov
- $HOME/gopath/bin/goveralls -coverprofile=merge.cov -service=travis-ci

# Build and prepare for deployment
- go build
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh

# Deploy steps never trigger on a new Pull Request. Deploy steps will trigger
# after a merge with matching "on:" conditions.
deploy:
######################################################################
## Service: annotation-service -- AppEngine Flexible Environment.
# INTEGRATION: Reviewed code, merged to integration branch, will trigger
# deployment to "standard" mlab-sandbox.
- provider: script
  script: $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-sandbox /tmp/mlab-sandbox.json
    $TRAVIS_BUILD_DIR/main annotator.yaml
  skip_cleanup: true
  on:
    repo: m-lab/annotation-service
    branch: integration

# STAGING: Should be used AFTER code review and commit to integration branch.  Triggers
# when *ANY* branch is tagged with staging-*'
# TODO(gfr) Update to be consistent across projects.  See https://github.com/m-lab/etl/issues/260
- provider: script
  script: $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-staging /tmp/mlab-staging.json
    $TRAVIS_BUILD_DIR/main annotator.yaml
  skip_cleanup: true
  on:
    repo: m-lab/annotation-service
    all_branches: true
    tag: true
    condition: $TRAVIS_TAG == staging-*

# PROD: Should be used AFTER code review and commit to master branch.  Triggers
# when *ANY* branch is tagged with prod-*'
- provider: script
  script: $TRAVIS_BUILD_DIR/travis/deploy_app.sh mlab-oti /tmp/mlab-oti.json $TRAVIS_BUILD_DIR/main
    annotator.yaml
  skip_cleanup: true
  on:
    repo: m-lab/annotation-service
    all_branches: true
    tag: true
    condition: $TRAVIS_TAG == prod-*
