language: go
sudo: required
script:
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh
  # //- source "${HOME}/google-cloud-sdk/path.bash.inc" && go test -v ./...
- export APPENGINE_DEV_APPSERVER="${HOME}/google-cloud-sdk/bin/dev_appserver.py" && source "${HOME}/google-cloud-sdk/bin/path.bash.inc" && go test -v ./...

go:
  - 1.6
  - 1.8
