language: go
sudo: required
script:
- export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json" && export APPENGINE_DEV_APPSERVER="${HOME}/google-cloud-sdk/bin/dev_appserver.py" && source "${HOME}/google-cloud-sdk/path.bash.inc" && go test -v ./... 
before_install:
- $TRAVIS_BUILD_DIR/annotator.sh
go:
- 1.6
- 1.8
