// Code generated by protoc-gen-go. DO NOT EDIT.
// source: location.proto

/*
Package annotator is a generated protocol buffer package.

It is generated from these files:
	location.proto

It has these top-level messages:
	Location
	LocationRequest
	LocationResponse
*/
package annotator

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	AreaCode      int32   `protobuf:"varint,1,opt,name=area_code,json=areaCode" json:"area_code,omitempty"`
	City          string  `protobuf:"bytes,2,opt,name=city" json:"city,omitempty"`
	ContinentCode string  `protobuf:"bytes,3,opt,name=continent_code,json=continentCode" json:"continent_code,omitempty"`
	CountryCode   string  `protobuf:"bytes,4,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	CountryCode3  string  `protobuf:"bytes,5,opt,name=country_code3,json=countryCode3" json:"country_code3,omitempty"`
	CountryName   string  `protobuf:"bytes,6,opt,name=country_name,json=countryName" json:"country_name,omitempty"`
	Latitude      float64 `protobuf:"fixed64,7,opt,name=latitude" json:"latitude,omitempty"`
	Longitude     float64 `protobuf:"fixed64,8,opt,name=longitude" json:"longitude,omitempty"`
	MetroCode     int32   `protobuf:"varint,9,opt,name=metro_code,json=metroCode" json:"metro_code,omitempty"`
	PostalCode    string  `protobuf:"bytes,10,opt,name=postal_code,json=postalCode" json:"postal_code,omitempty"`
	Region        string  `protobuf:"bytes,11,opt,name=region" json:"region,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Location) GetAreaCode() int32 {
	if m != nil {
		return m.AreaCode
	}
	return 0
}

func (m *Location) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Location) GetContinentCode() string {
	if m != nil {
		return m.ContinentCode
	}
	return ""
}

func (m *Location) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Location) GetCountryCode3() string {
	if m != nil {
		return m.CountryCode3
	}
	return ""
}

func (m *Location) GetCountryName() string {
	if m != nil {
		return m.CountryName
	}
	return ""
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetMetroCode() int32 {
	if m != nil {
		return m.MetroCode
	}
	return 0
}

func (m *Location) GetPostalCode() string {
	if m != nil {
		return m.PostalCode
	}
	return ""
}

func (m *Location) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

type LocationRequest struct {
	IP_Addr   string `protobuf:"bytes,1,opt,name=IP_Addr,json=IPAddr" json:"IP_Addr,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *LocationRequest) Reset()                    { *m = LocationRequest{} }
func (m *LocationRequest) String() string            { return proto.CompactTextString(m) }
func (*LocationRequest) ProtoMessage()               {}
func (*LocationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LocationRequest) GetIP_Addr() string {
	if m != nil {
		return m.IP_Addr
	}
	return ""
}

func (m *LocationRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type LocationResponse struct {
	Found_Location *Location `protobuf:"bytes,1,opt,name=Found_Location,json=FoundLocation" json:"Found_Location,omitempty"`
}

func (m *LocationResponse) Reset()                    { *m = LocationResponse{} }
func (m *LocationResponse) String() string            { return proto.CompactTextString(m) }
func (*LocationResponse) ProtoMessage()               {}
func (*LocationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LocationResponse) GetFound_Location() *Location {
	if m != nil {
		return m.Found_Location
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "annotator.Location")
	proto.RegisterType((*LocationRequest)(nil), "annotator.LocationRequest")
	proto.RegisterType((*LocationResponse)(nil), "annotator.LocationResponse")
}

func init() { proto.RegisterFile("location.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4d, 0x6b, 0xfa, 0x40,
	0x10, 0xc6, 0x89, 0x2f, 0x31, 0x3b, 0x51, 0xff, 0x7f, 0xb6, 0xd0, 0x86, 0xbe, 0x50, 0x6b, 0x29,
	0x78, 0xf2, 0x50, 0x6f, 0xbd, 0x95, 0x42, 0xa9, 0x50, 0x44, 0xf2, 0x05, 0x64, 0x9b, 0x0c, 0x12,
	0x48, 0x76, 0xd2, 0xcd, 0xe4, 0xe0, 0xa7, 0xed, 0x57, 0x29, 0x4e, 0x34, 0xda, 0x5b, 0xe6, 0x79,
	0x7e, 0xf3, 0x64, 0x76, 0x76, 0x61, 0x9c, 0x53, 0x62, 0x38, 0x23, 0x3b, 0x2f, 0x1d, 0x31, 0x69,
	0x65, 0xac, 0x25, 0x36, 0x4c, 0x6e, 0xfa, 0xd3, 0x81, 0xe0, 0xf3, 0xe0, 0xea, 0x1b, 0x50, 0xc6,
	0xa1, 0xd9, 0x24, 0x94, 0x62, 0xe4, 0x4d, 0xbc, 0x59, 0x3f, 0x0e, 0xf6, 0xc2, 0x1b, 0xa5, 0xa8,
	0x35, 0xf4, 0x92, 0x8c, 0x77, 0x51, 0x67, 0xe2, 0xcd, 0x54, 0x2c, 0xdf, 0xfa, 0x09, 0xc6, 0x09,
	0x59, 0xce, 0x2c, 0x5a, 0x6e, 0xba, 0xba, 0xe2, 0x8e, 0x5a, 0x55, 0x5a, 0x1f, 0x60, 0x98, 0x50,
	0x6d, 0xd9, 0xed, 0x1a, 0xa8, 0x27, 0x50, 0x78, 0xd0, 0x04, 0x79, 0x84, 0xd1, 0x39, 0xb2, 0x88,
	0xfa, 0xc2, 0x0c, 0xcf, 0x98, 0xc5, 0x79, 0x8e, 0x35, 0x05, 0x46, 0xfe, 0x9f, 0x9c, 0x95, 0x29,
	0x50, 0x5f, 0x43, 0x90, 0x1b, 0xce, 0xb8, 0x4e, 0x31, 0x1a, 0x4c, 0xbc, 0x99, 0x17, 0xb7, 0xb5,
	0xbe, 0x05, 0x95, 0x93, 0xdd, 0x36, 0x66, 0x20, 0xe6, 0x49, 0xd0, 0x77, 0x00, 0x05, 0xb2, 0xa3,
	0x66, 0x44, 0x25, 0xa7, 0x57, 0xa2, 0xc8, 0x80, 0xf7, 0x10, 0x96, 0x54, 0xb1, 0xc9, 0x1b, 0x1f,
	0xe4, 0xd7, 0xd0, 0x48, 0x02, 0x5c, 0x82, 0xef, 0x70, 0x9b, 0x91, 0x8d, 0x42, 0xf1, 0x0e, 0xd5,
	0xf4, 0x03, 0xfe, 0x1d, 0x17, 0x1c, 0xe3, 0x77, 0x8d, 0x15, 0xeb, 0x2b, 0x18, 0x2c, 0xd7, 0x9b,
	0xd7, 0x34, 0x75, 0xb2, 0x65, 0x15, 0xfb, 0xcb, 0xf5, 0xbe, 0xda, 0x4f, 0xc8, 0x59, 0x81, 0x15,
	0x9b, 0xa2, 0x94, 0x45, 0x77, 0xe3, 0x93, 0x30, 0x5d, 0xc1, 0xff, 0x53, 0x52, 0x55, 0x92, 0xad,
	0x50, 0xbf, 0xc0, 0xf8, 0x9d, 0x6a, 0x9b, 0x6e, 0x8e, 0x8e, 0x24, 0x86, 0xcf, 0x17, 0xf3, 0xf6,
	0x8e, 0xe7, 0x6d, 0xd3, 0x48, 0xd0, 0x63, 0xf9, 0xe5, 0xcb, 0x6b, 0x58, 0xfc, 0x06, 0x00, 0x00,
	0xff, 0xff, 0xa8, 0xa0, 0x86, 0x2b, 0x1f, 0x02, 0x00, 0x00,
}
